import 'package:firebase_core/firebase_core.dart';

/// The marker the committed `lib/firebase_options.dart` ships instead of a real
/// Firebase project. Written both bare and wrapped in angle brackets, so match
/// on a substring rather than equality.
const String firebaseOptionsPlaceholderMarker = 'THIS_IS_AUTOGENERATED';

/// Whether [options] are still the committed placeholders.
///
/// Worth checking before [Firebase.initializeApp]: on Apple platforms
/// `FIRApp` validates the app ID and raises an Objective-C exception on a
/// malformed one. That exception crosses the platform channel uncaught, so it
/// takes the process down rather than surfacing as a Dart error the caller
/// could handle.
bool isPlaceholderFirebaseOptions(FirebaseOptions options) =>
    <String?>[options.appId, options.apiKey, options.projectId].any(
      (value) =>
          value != null && value.contains(firebaseOptionsPlaceholderMarker),
    );
