import 'dart:convert';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:web_dex/bloc/analytics/firebase_options_placeholders.dart';

/// Guards the committed Firebase configuration on Apple platforms.
///
/// Two separate things have to stay true, and neither is visible in a diff
/// review of the file that breaks it:
///
/// 1. No real project values are committed. `flutterfire configure` rewrites
///    these files in place as a side effect of pointing local tooling at a
///    Firebase project, so they land in a working tree without anyone
///    deciding to publish them. That happened once already, and shipped a
///    live API key in the macOS release artifact.
/// 2. No `GoogleService-Info.plist` is copied into the app bundle. FirebaseCore
///    reads a bundled plist at plugin registration and raises on a malformed
///    `GOOGLE_APP_ID`, which crashes the app at launch, before Dart runs and
///    outside any error handling the app could install.
const List<String> _plistPaths = <String>[
  'ios/Runner/GoogleService-Info.plist',
  'macos/Runner/GoogleService-Info.plist',
];

const List<String> _appIdFilePaths = <String>[
  'ios/firebase_app_id_file.json',
  'macos/firebase_app_id_file.json',
];

const List<String> _pbxprojPaths = <String>[
  'ios/Runner.xcodeproj/project.pbxproj',
  'macos/Runner.xcodeproj/project.pbxproj',
];

/// Values a real Firebase project has and a placeholder does not: a Google API
/// key, and a well-formed `1:<project number>:<platform>:<hash>` app ID.
final RegExp _googleApiKey = RegExp(r'AIza[0-9A-Za-z_-]{30,}');
final RegExp _realAppId = RegExp(r'\b1:\d+:[a-z]+:[0-9a-f]+\b');

String _read(String path) {
  final file = File(path);
  expect(file.existsSync(), isTrue, reason: '$path should exist');
  return file.readAsStringSync();
}

void main() {
  group('Apple Firebase config:', () {
    test('the committed plists carry no real project values', () {
      for (final path in _plistPaths) {
        final source = _read(path);
        expect(
          _googleApiKey.hasMatch(source),
          isFalse,
          reason: '$path contains a real Google API key',
        );
        expect(
          _realAppId.hasMatch(source),
          isFalse,
          reason: '$path contains a real Firebase app ID',
        );
        expect(
          source.contains(firebaseOptionsPlaceholderMarker),
          isTrue,
          reason: '$path should still hold the placeholder markers',
        );
      }
    });

    test('the committed app-id files carry no real project values', () {
      for (final path in _appIdFilePaths) {
        final values = (jsonDecode(_read(path)) as Map<String, dynamic>).map(
          (key, value) => MapEntry(key, '$value'),
        );

        for (final key in <String>[
          'GOOGLE_APP_ID',
          'FIREBASE_PROJECT_ID',
          'GCM_SENDER_ID',
        ]) {
          expect(
            values[key],
            contains(firebaseOptionsPlaceholderMarker),
            reason: '$path: $key should still be a placeholder',
          );
        }
      }
    });

    test('no Xcode target copies GoogleService-Info.plist into the bundle', () {
      for (final path in _pbxprojPaths) {
        expect(
          _read(path),
          isNot(contains('GoogleService-Info.plist in Resources')),
          reason:
              '$path bundles the placeholder plist; FirebaseCore will raise on '
              'its GOOGLE_APP_ID at launch',
        );
      }
    });

    test('placeholder options are recognised in both spellings', () {
      // firebase_options.dart writes `<THIS_IS_AUTOGENERATED>`; the plists
      // write it bare.
      for (final marker in <String>[
        firebaseOptionsPlaceholderMarker,
        '<$firebaseOptionsPlaceholderMarker>',
      ]) {
        expect(
          isPlaceholderFirebaseOptions(
            FirebaseOptions(
              apiKey: marker,
              appId: marker,
              messagingSenderId: marker,
              projectId: marker,
            ),
          ),
          isTrue,
          reason: '$marker should be treated as unconfigured',
        );
      }
    });

    test('a placeholder in any single field is enough to skip init', () {
      const real = FirebaseOptions(
        apiKey: 'AIzaSyExampleExampleExampleExampleExample',
        appId: '1:000000000000:ios:0000000000000000',
        messagingSenderId: '000000000000',
        projectId: 'example-project',
      );

      expect(isPlaceholderFirebaseOptions(real), isFalse);
      expect(
        isPlaceholderFirebaseOptions(
          FirebaseOptions(
            apiKey: real.apiKey,
            appId: '<$firebaseOptionsPlaceholderMarker>',
            messagingSenderId: real.messagingSenderId,
            projectId: real.projectId,
          ),
        ),
        isTrue,
      );
      expect(
        isPlaceholderFirebaseOptions(
          FirebaseOptions(
            apiKey: '<$firebaseOptionsPlaceholderMarker>',
            appId: real.appId,
            messagingSenderId: real.messagingSenderId,
            projectId: real.projectId,
          ),
        ),
        isTrue,
      );
    });
  });
}
